import mongoose from "mongoose";

const orderSchema = new mongoose.Schema(
  {
    user: { type: mongoose.Schema.Types.ObjectId, ref: "User", required: true },
    productName: { type: String, required: true },
    memory: { type: String, required: true },
    price: { type: Number, required: true },
    originalPrice: { type: Number },
    promoCode: { type: String },
    promoDiscount: { type: Number, default: 0 },
    ipStockId: { type: String },
    slotIpPackageId: { type: String },
    slotIpId: { type: String },
    transactionId: { type: String, default: "" },
    status: { type: String, default: "pending" },
    ipAddress: { type: String, default: "" },
    username: { type: String, default: "" },
    password: { type: String, default: "" },
    os: {
      type: String,
      default: "Ubuntu 22",
    },
    clientTxnId: { type: String, required: true, unique: true },
    gatewayOrderId: { type: String },
    expiryDate: { type: Date },
    customerName: { type: String },
    customerEmail: { type: String },
    webhookAmount: { type: String },
    webhookCustomerName: { type: String },
    webhookCustomerEmail: { type: String },
    provider: {
      type: String,
      enum: ["hostycare", "smartvps", "slotip", "advps"],
      default: "hostycare",
    },
    hostycareServiceId: { type: String },
    hostycareProductId: { type: String },
    smartvpsServiceId: { type: String },
    smartvpsProductId: { type: String },
    advpsServiceId: { type: String },
    advpsProductId: { type: String },
    advpsOrderId: { type: String },
    advpsRebuildCount: { type: Number, default: 0 },
    advpsRebuildCountMonth: { type: String, default: "" },
    provisioningStatus: {
      type: String,
      enum: ["pending", "provisioning", "active", "failed", "suspended", "terminated"],
      default: "pending",
    },
    provisioningError: { type: String, default: "" },
    autoProvisioned: { type: Boolean, default: false },
    lastProvisionAttempt: { type: Date },
    paymentMethod: { type: String },
    paymentDetails: { type: mongoose.Schema.Types.Mixed },
    lastAction: { type: String },
    lastActionTime: { type: Date },
    lastSyncTime: { type: Date },
    serverDetails: {
      lastUpdated: { type: Date },
      rawDetails: { type: mongoose.Schema.Types.Mixed },
      rawInfo: { type: mongoose.Schema.Types.Mixed },
    },
    renewalPayments: [
      {
        paymentId: { type: String, required: true },
        amount: { type: Number, required: true },
        paidAt: { type: Date, required: true },
        previousExpiry: { type: Date, required: true },
        newExpiry: { type: Date, required: true },
        renewalTxnId: { type: String, required: true },
      },
    ],
    pendingRenewal: {
      renewalTxnId: { type: String },
      initiatedAt: { type: Date },
      paymentMethod: { type: String },
      amount: { type: Number },
      gatewayOrderId: { type: String },
    },
    panelUsername: { type: String, sparse: true },
    panelPassword: { type: String },
    resellerId: { type: mongoose.Schema.Types.ObjectId, ref: "Reseller", index: true },
    pricing: {
      basePrice: Number,
      resellerPrice: Number,
      customerPrice: Number,
      markup: Number,
    },
    walletDeduction: {
      deducted: { type: Boolean, default: false },
      amount: Number,
      transactionId: String,
      timestamp: Date,
    },
    apiOrderId: String,
    apiMetadata: mongoose.Schema.Types.Mixed,
  },
  { timestamps: true }
);

orderSchema.index({ panelUsername: 1 });

export default mongoose.models.Order || mongoose.model("Order", orderSchema);
